### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by HAYASHI0884** [HAYASHI0884/furima-31115#10]
* URL
https://furima-31115.herokuapp.com/
* basic認証
hayashi / 1023
* 出品者用のメールアドレスとパスワード
aaa@gmail.com / 111aaa
* 購入者用のメールアドレスとパスワード
bbb@gmail.com / 111aaa
* 購入用カードの番号・期限・セキュリティコード
4242424242424242 / 3.23 / 123

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by HAYASHI0884** [comment]
レビューありがとうございます！
承知いたしました。引き続き頑張ってまいります。
